class ReminderUiText {
  const ReminderUiText._();

  static const appTitle = 'Reminder App';
  static const homeTitle = '首頁';
  static const manageTitle = '管理';
  static const historyTitle = '歷史紀錄';
  static const taskTemplateTitle = 'Task Templates';
  static const timelineTitle = 'Timelines';
  static const todayTab = 'Today';
  static const upcomingTab = 'Upcoming';
  static const overdueTab = 'Overdue';
  static const historyTab = 'History';
  static const addTask = '新增 Task';
  static const addTaskTemplate = '新增 Task Template';
  static const addTimeline = '新增 Timeline';
  static const editTask = '編輯 Task';
  static const editTaskTemplate = '編輯 Task Template';
  static const editTimeline = '編輯 Timeline';
  static const noTodayItems = '今天沒有 Task 或 Milestone。';
  static const noUpcomingItems = '接下來沒有排程中的內容。';
  static const noOverdueItems = '目前沒有逾期 Task。';
  static const noHistoryItems = '目前沒有歷史紀錄。';
  static const noTaskHistory = '目前沒有 Task History。';
  static const noMilestoneHistory = '目前沒有 Milestone History。';
  static const noTemplates = '目前沒有 Task Template。';
  static const noTimelines = '目前沒有 Timeline。';
  static const manageAction = '管理';
  static const historyAction = '歷史紀錄';
  static const saveAction = '儲存';
  static const addMilestoneAction = '新增 Milestone';
  static const customMilestoneTitle = 'Custom Milestones';
  static const ruleBasedMilestoneTitle = 'Rule-based Milestones';
  static const taskHistoryTitle = 'Task History';
  static const milestoneHistoryTitle = 'Milestone History';
  static const completeAction = '完成';
  static const skipAction = '跳過';
  static const cancelAction = '取消';
  static const deferAction = '延期 1 天';
  static const noticedAction = '已看過';
  static const pausedLabel = 'Paused';
  static const archivedLabel = 'Archived';
}
