class ReminderUiText {
  const ReminderUiText._();

  static const appTitle = 'Reminder App';
  static const homeTitle = '首頁';
  static const manageTitle = '管理';
  static const featureAction = '功能';
  static const featurePageTitle = '功能頁';
  static const itemPackTitle = 'Item Packs';
  static const itemTitle = 'Items';
  static const timelineTitle = 'Timelines';
  static const itemActivityFeatureTitle = '動態（for item）';
  static const itemsManagementFeatureTitle = 'Items 管理';
  static const itemPacksManagementFeatureTitle = 'Item Packs 管理';
  static const timelineManagementFeatureTitle = 'Timeline 管理';
  static const userSettingsFeatureTitle = '設定頁(for user）';
  static const developerSettingsFeatureTitle = '開發者設定';
  static const dangerTab = 'Danger';
  static const warningTab = 'Warning';
  static const timelineTab = 'Timeline';
  static const addItem = '新增 Item';
  static const addItemPack = '新增 Item Pack';
  static const addTimeline = '新增 Timeline';
  static const editItem = '編輯 Item';
  static const editItemPack = '編輯 Item Pack';
  static const editTimeline = '編輯 Timeline';
  static const noDangerItems = '目前沒有 danger item。';
  static const noWarningItems = '目前沒有 warning item。';
  static const noUpcomingTimelineItems = '目前沒有 upcoming timeline milestone。';
  static const noItemHistory = '此輪 core model 不保留 item completion history。';
  static const noMilestoneHistory = '目前沒有 Milestone History。';
  static const noItems = '目前沒有 Item。';
  static const noItemPacks = '目前沒有 Item Pack。';
  static const noTimelines = '目前沒有 Timeline。';
  static const noDefaultItemPack = '目前沒有 Default Item Pack。';
  static const manageAction = '管理';
  static const saveAction = '儲存';
  static const saveFailedPrefix = '儲存失敗';
  static const itemSaveFailedMessage = '此 Item 已不存在或目前不可儲存。';
  static const timelineSaveFailedMessage = '此 Timeline 已不存在或目前不可儲存。';
  static const archivePackConfirmTitle = '封存 Item Pack';
  static const archivePackConfirmMessage =
      '此 Item Pack 仍有 active 或 paused items。封存後，底下 items 會全部一併封存。';
  static const addRuleAction = '新增 Rule';
  static const milestoneRulesTitle = 'Milestone Rules';
  static const upcomingMilestonesTitle = 'Upcoming Milestones';
  static const milestoneHistoryTitle = 'Milestone History';
  static const timelineMilestoneHistoryTitle = 'Timeline Milestone History';
  static const noTimelineUpcomingMilestone = '目前沒有 upcoming milestone。';
  static const noTimelineMilestoneHistory =
      '此 Timeline 目前沒有 milestone history。';
  static const itemActivityPlaceholderMessage = '此頁為 UI 空殼，尚未接上 item 動態資料。';
  static const itemsManagementPlaceholderMessage = '此頁為 UI 空殼，尚未接上 Items 管理資料。';
  static const itemPacksManagementPlaceholderMessage =
      '此頁為 UI 空殼，尚未接上 Item Packs 管理資料。';
  static const timelineManagementPlaceholderMessage =
      '此頁為 UI 空殼，尚未接上 Timeline 管理資料。';
  static const userSettingsPlaceholderMessage = '此頁為 UI 空殼，尚未接上使用者設定資料。';
  static const developerSettingsPlaceholderMessage = '此頁為 UI 空殼，尚未接上開發者設定資料。';
  static const developerPreviewDateTitle = '當前日期';
  static const developerPreviewDateCurrentLabel = '目前生效日期';
  static const developerPreviewDateOverrideStatusLabel = '覆蓋狀態';
  static const developerPreviewDateOverrideEnabled = '已啟用';
  static const developerPreviewDateOverrideDisabled = '使用真實今天';
  static const developerPreviewDatePickAction = '選擇日期';
  static const developerPreviewDateResetAction = '還原今天';
  static const nextMilestoneLabel = '下一筆';
  static const completeAction = '完成';
  static const skipAction = '跳過';
  static const noticedAction = '已看過';
  static const editAction = '編輯';
  static const pauseAction = '暫停';
  static const resumeAction = '恢復';
  static const archiveAction = '封存';
  static const viewAllAction = '查看全部';
  static const collapseAction = '收起';
  static const updatedAtLabel = '最後更新';
  static const previousPageAction = '上一頁';
  static const nextPageAction = '下一頁';
  static const systemDefaultPackLabel = '系統預設';
  static const unassignedPackOption = '未指定（將使用系統預設 pack）';
  static const archivedPackSuffix = 'archived';
  static const emptyPackHint = '此 item pack 目前沒有 item。';
  static const packTitleFieldLabel = 'Pack Title';
  static const packDescriptionFieldLabel = 'Pack Description';
  static const itemCountLabel = 'items';
  static const packFieldLabel = 'Pack';
}
